
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	1 channel, 959904 bytes/channel
 *	Total Size: 1 * 959904 + 4 (header) = 959948 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jihan\Documents\School\2018 Spring\CS 2261\Final Project\M04\gameSong.wav
 *	Time-stamp: Thu Apr 12 21:56:02 2018
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 959904

extern const unsigned char gameSong[959904];

#endif /* __GAMESONGH__ */
