
/**************************************************************
 *	
 *	growlFX, 8 bit, 11025Hz,
 *	1 channel, 47808 bytes/channel
 *	Total Size: 1 * 47808 + 4 (header) = 47852 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jihan\Documents\School\2018 Spring\CS 2261\Final Project\FinalV3\growlFX.aiff
 *	Time-stamp: Sun Apr 15 11:10:40 2018
 *	
 **************************************************************/

#ifndef __GROWLFXH__
#define __GROWLFXH__

#define GROWLFXFREQ 11025
#define GROWLFXLEN 47808

extern const unsigned char growlFX[47808];

#endif /* __GROWLFXH__ */
