
/**************************************************************
 *	
 *	introSong, 8 bit, 11025Hz,
 *	1 channel, 262824 bytes/channel
 *	Total Size: 1 * 262824 + 4 (header) = 262868 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jihan\Documents\School\2018 Spring\CS 2261\Final Project\FinalV3\introSong.aiff
 *	Time-stamp: Sun Apr 15 11:02:54 2018
 *	
 **************************************************************/

#ifndef __INTROSONGH__
#define __INTROSONGH__

#define INTROSONGFREQ 11025
#define INTROSONGLEN 262824

extern const unsigned char introSong[262824];

#endif /* __INTROSONGH__ */
