
/**************************************************************
 *	
 *	loseSong, 8 bit, 11025Hz,
 *	1 channel, 797075 bytes/channel
 *	Total Size: 1 * 797075 + 4 (header) = 797119 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jihan\Documents\School\2018 Spring\CS 2261\Final Project\M04\loseSong.wav
 *	Time-stamp: Thu Apr 12 22:16:41 2018
 *	
 **************************************************************/

#ifndef __LOSESONGH__
#define __LOSESONGH__

#define LOSESONGFREQ 11025
#define LOSESONGLEN 797075

extern const unsigned char loseSong[797075];

#endif /* __LOSESONGH__ */
