
/**************************************************************
 *	
 *	startSong, 8 bit, 11025Hz,
 *	1 channel, 1428115 bytes/channel
 *	Total Size: 1 * 1428115 + 4 (header) = 1428159 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jihan\Documents\School\2018 Spring\CS 2261\Final Project\M04\startSong.wav
 *	Time-stamp: Thu Apr 12 22:16:20 2018
 *	
 **************************************************************/

#ifndef __STARTSONGH__
#define __STARTSONGH__

#define STARTSONGFREQ 11025
#define STARTSONGLEN 1428115

extern const unsigned char startSong[1428115];

#endif /* __STARTSONGH__ */
