
/**************************************************************
 *	
 *	winSong, 8 bit, 44100Hz,
 *	1 channel, 5817769 bytes/channel
 *	Total Size: 1 * 5817769 + 4 (header) = 5817813 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jihan\Documents\School\2018 Spring\CS 2261\Final Project\M04\winSong.wav
 *	Time-stamp: Thu Apr 12 22:16:35 2018
 *	
 **************************************************************/

#ifndef __WINSONGH__
#define __WINSONGH__

#define WINSONGFREQ 44100
#define WINSONGLEN 5817769

extern const unsigned char winSong[5817769];

#endif /* __WINSONGH__ */
